name: Auto merge main to prod when a PR is merged to main
run-name: Create PR to update prod with main.
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  make_pr_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: "gh pr create -H prod -B main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}